# Generated by Django 4.2.23 on 2025-08-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_architecture', models.CharField(choices=[('transformer', 'Transformer'), ('gpt', 'GPT'), ('llama', 'LLaMA'), ('bert', 'BERT'), ('other', 'Other')], default='transformer', max_length=50, verbose_name='Model Architecture')),
                ('checkpoint', models.CharField(help_text='Hugging Face model name or path', max_length=200, verbose_name='Checkpoint (Hugging Face Model)')),
                ('parameters_in_billions', models.FloatField(verbose_name='Parameters (Billions)')),
                ('fine_tuning', models.TextField(blank=True, verbose_name='Fine-Tuning Details')),
                ('context_of_behavior', models.TextField(verbose_name='Context of Behavior')),
                ('name', models.CharField(max_length=100, verbose_name='Agent Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
    ]
