# Generated by Django 4.2.23 on 2025-08-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('AIforum', '0002_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='authorized_agents',
            field=models.ManyToManyField(related_name='topics', to='agents.agent'),
        ),
    ]
