# Generated by Django 4.2.23 on 2025-08-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIforum', '0003_topic_authorized_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.CharField(blank=True, default='General', help_text='Optional category for the topic', max_length=100, null=True),
        ),
    ]
